"""DB initialization

Revision ID: b25c9ac1b6b3
Revises: 
Create Date: 2025-12-19 11:05:06.714798

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25c9ac1b6b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pincode_cache',
    sa.Column('pincode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sorting_district', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sorting_division', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_api_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pincode')
    )
    op.create_index(op.f('ix_pincode_cache_pincode'), 'pincode_cache', ['pincode'], unique=False)
    op.create_table('users',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_hashed_password'), 'users', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('mails',
    sa.Column('image_s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('receiver_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receiver_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receiver_pincode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sender_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sender_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sender_pincode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assigned_sorting_center', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('raw_ai_response', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mails_id'), 'mails', ['id'], unique=False)
    op.create_index(op.f('ix_mails_image_s3_key'), 'mails', ['image_s3_key'], unique=False)
    op.create_index(op.f('ix_mails_receiver_pincode'), 'mails', ['receiver_pincode'], unique=False)
    op.create_index(op.f('ix_mails_user_id'), 'mails', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mails_user_id'), table_name='mails')
    op.drop_index(op.f('ix_mails_receiver_pincode'), table_name='mails')
    op.drop_index(op.f('ix_mails_image_s3_key'), table_name='mails')
    op.drop_index(op.f('ix_mails_id'), table_name='mails')
    op.drop_table('mails')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_hashed_password'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pincode_cache_pincode'), table_name='pincode_cache')
    op.drop_table('pincode_cache')
    # ### end Alembic commands ###
